-- farm_metric_sets_seed_history  (M1)
-- Which metric columns appear for which crop + season + scenario, derived
-- deterministically from the workbook's per-season blocks (scripts/parse_metric_sets.js).
-- Idempotent: safe to re-run. 28 sets, 139 items.
-- Mango&Pomegranate share one sheet; VRM + condemned are seeded to pomegranate only (§3.3).

insert into public.farm_metric_sets (product_id, season_year, scenario, notes) values
  ('citrus', 2018, 'actual', 'Citrus 2018'),
  ('citrus', 2019, 'actual', 'Citrus 2019'),
  ('citrus', 2020, 'actual', 'Citrus 2020'),
  ('citrus', 2021, 'actual', 'Citrus 2021'),
  ('citrus', 2022, 'actual', 'Citrus 2022'),
  ('citrus', 2023, 'actual', 'Citrus 2023'),
  ('citrus', 2024, 'actual', 'Citrus 2024'),
  ('citrus', 2025, 'actual', 'Citrus 2025'),
  ('grapes', 2017, 'actual', 'Grapes 2017'),
  ('grapes', 2018, 'actual', 'Grapes 2018'),
  ('grapes', 2019, 'actual', 'Grapes 2019'),
  ('grapes', 2020, 'actual', 'Grapes 2020'),
  ('grapes', 2021, 'actual', 'Grapes 2021'),
  ('grapes', 2022, 'actual', 'Grapes 2022'),
  ('grapes', 2023, 'actual', 'Grapes 2023'),
  ('grapes', 2023, 'plan', 'Grapes 2023 (plan)'),
  ('grapes', 2024, 'actual', 'Grapes 2024'),
  ('grapes', 2024, 'plan', 'Grapes 2024 (plan)'),
  ('grapes', 2025, 'actual', 'Grapes 2025'),
  ('grapes', 2025, 'plan', 'Grapes 2025 (plan)'),
  ('mango', 2022, 'actual', 'Mango 2022'),
  ('mango', 2023, 'actual', 'Mango 2023'),
  ('mango', 2023, 'plan', 'Mango 2023 (plan)'),
  ('mango', 2024, 'actual', 'Mango 2024'),
  ('pomegranate', 2022, 'actual', 'Pomegranate 2022'),
  ('pomegranate', 2023, 'actual', 'Pomegranate 2023'),
  ('pomegranate', 2023, 'plan', 'Pomegranate 2023 (plan)'),
  ('pomegranate', 2024, 'actual', 'Pomegranate 2024')
on conflict (product_id, season_year, scenario) do update set notes = excluded.notes;

insert into public.farm_metric_set_items (metric_set_id, metric_id, sort_order, required)
select ms.id, m.id, v.ord, false
from (values
  ('citrus', 2018, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2018, 'actual', 'export_packhouse', 2),
  ('citrus', 2018, 'actual', 'packhouse_reject', 3),
  ('citrus', 2018, 'actual', 'local_sales_combined', 4),
  ('citrus', 2018, 'actual', 'actual_production', 5),
  ('citrus', 2019, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2019, 'actual', 'export_packhouse', 2),
  ('citrus', 2019, 'actual', 'packhouse_reject', 3),
  ('citrus', 2019, 'actual', 'local_sales_combined', 4),
  ('citrus', 2019, 'actual', 'actual_production', 5),
  ('citrus', 2020, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2020, 'actual', 'export_packhouse', 2),
  ('citrus', 2020, 'actual', 'packhouse_reject', 3),
  ('citrus', 2020, 'actual', 'local_sales_combined', 4),
  ('citrus', 2020, 'actual', 'actual_production', 5),
  ('citrus', 2021, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2021, 'actual', 'export_packhouse', 2),
  ('citrus', 2021, 'actual', 'packhouse_reject', 3),
  ('citrus', 2021, 'actual', 'raw_to_traders', 4),
  ('citrus', 2021, 'actual', 'field_reject_sales', 5),
  ('citrus', 2021, 'actual', 'actual_production', 6),
  ('citrus', 2022, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2022, 'actual', 'export_packhouse', 2),
  ('citrus', 2022, 'actual', 'export_supermarket_gifts', 3),
  ('citrus', 2022, 'actual', 'weight_loss', 4),
  ('citrus', 2022, 'actual', 'export_total', 5),
  ('citrus', 2022, 'actual', 'packhouse_reject', 6),
  ('citrus', 2022, 'actual', 'raw_to_traders', 7),
  ('citrus', 2022, 'actual', 'field_reject_sales', 8),
  ('citrus', 2022, 'actual', 'actual_production', 9),
  ('citrus', 2023, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2023, 'actual', 'export_packhouse', 2),
  ('citrus', 2023, 'actual', 'packhouse_reject', 3),
  ('citrus', 2023, 'actual', 'export_supermarket_gifts', 4),
  ('citrus', 2023, 'actual', 'shortage_dryout', 5),
  ('citrus', 2023, 'actual', 'raw_to_traders', 6),
  ('citrus', 2023, 'actual', 'field_reject_sales', 7),
  ('citrus', 2023, 'actual', 'actual_production', 8),
  ('citrus', 2024, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2024, 'actual', 'export_packhouse', 2),
  ('citrus', 2024, 'actual', 'export_carton', 3),
  ('citrus', 2024, 'actual', 'packhouse_reject', 4),
  ('citrus', 2024, 'actual', 'export_supermarket', 5),
  ('citrus', 2024, 'actual', 'dry_weight', 6),
  ('citrus', 2024, 'actual', 'export_gifts', 7),
  ('citrus', 2024, 'actual', 'weight_loss_damaged', 8),
  ('citrus', 2024, 'actual', 'raw_to_traders', 9),
  ('citrus', 2024, 'actual', 'field_reject_sales', 10),
  ('citrus', 2024, 'actual', 'actual_production', 11),
  ('citrus', 2025, 'actual', 'raw_to_packhouse', 1),
  ('citrus', 2025, 'actual', 'export_packhouse', 2),
  ('citrus', 2025, 'actual', 'packhouse_reject', 3),
  ('citrus', 2025, 'actual', 'raw_to_traders', 4),
  ('citrus', 2025, 'actual', 'field_reject_sales', 5),
  ('citrus', 2025, 'actual', 'actual_production', 6),
  ('grapes', 2017, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2017, 'actual', 'export_packhouse', 2),
  ('grapes', 2017, 'actual', 'local_sales_combined', 3),
  ('grapes', 2017, 'actual', 'actual_production', 4),
  ('grapes', 2018, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2018, 'actual', 'export_packhouse', 2),
  ('grapes', 2018, 'actual', 'local_sales_combined', 3),
  ('grapes', 2018, 'actual', 'actual_production', 4),
  ('grapes', 2019, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2019, 'actual', 'export_packhouse', 2),
  ('grapes', 2019, 'actual', 'local_sales_combined', 3),
  ('grapes', 2019, 'actual', 'actual_production', 4),
  ('grapes', 2020, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2020, 'actual', 'export_packhouse', 2),
  ('grapes', 2020, 'actual', 'local_sales_combined', 3),
  ('grapes', 2020, 'actual', 'actual_production', 4),
  ('grapes', 2021, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2021, 'actual', 'export_packhouse', 2),
  ('grapes', 2021, 'actual', 'local_sales_combined', 3),
  ('grapes', 2021, 'actual', 'actual_production', 4),
  ('grapes', 2022, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2022, 'actual', 'export_packhouse', 2),
  ('grapes', 2022, 'actual', 'local_sales_combined', 3),
  ('grapes', 2022, 'actual', 'actual_production', 4),
  ('grapes', 2023, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2023, 'actual', 'export_packhouse', 2),
  ('grapes', 2023, 'actual', 'farm_gate_sales', 3),
  ('grapes', 2023, 'actual', 'actual_production', 4),
  ('grapes', 2023, 'plan', 'plan_raw_to_packhouse', 1),
  ('grapes', 2023, 'plan', 'plan_export', 2),
  ('grapes', 2023, 'plan', 'plan_local_sales', 3),
  ('grapes', 2023, 'plan', 'planned_production', 4),
  ('grapes', 2024, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2024, 'actual', 'export_packhouse', 2),
  ('grapes', 2024, 'actual', 'export_carton', 3),
  ('grapes', 2024, 'actual', 'farm_gate_sales', 4),
  ('grapes', 2024, 'actual', 'actual_production', 5),
  ('grapes', 2024, 'plan', 'plan_raw_to_packhouse', 1),
  ('grapes', 2024, 'plan', 'plan_export', 2),
  ('grapes', 2024, 'plan', 'plan_local_sales', 3),
  ('grapes', 2024, 'plan', 'planned_production', 4),
  ('grapes', 2025, 'actual', 'raw_to_packhouse', 1),
  ('grapes', 2025, 'actual', 'export_packhouse', 2),
  ('grapes', 2025, 'actual', 'export_carton', 3),
  ('grapes', 2025, 'actual', 'export_supermarket', 4),
  ('grapes', 2025, 'actual', 'dry_weight', 5),
  ('grapes', 2025, 'actual', 'packhouse_reject', 6),
  ('grapes', 2025, 'actual', 'farm_gate_sales', 7),
  ('grapes', 2025, 'actual', 'actual_production', 8),
  ('grapes', 2025, 'plan', 'plan_raw_to_packhouse', 1),
  ('grapes', 2025, 'plan', 'plan_export', 2),
  ('grapes', 2025, 'plan', 'planned_production', 3),
  ('mango', 2022, 'actual', 'raw_to_packhouse', 1),
  ('mango', 2022, 'actual', 'export_packhouse', 2),
  ('mango', 2022, 'actual', 'export_supermarket', 3),
  ('mango', 2022, 'actual', 'local_sales_combined', 4),
  ('mango', 2022, 'actual', 'actual_production', 5),
  ('mango', 2023, 'actual', 'raw_to_packhouse', 1),
  ('mango', 2023, 'actual', 'export_packhouse', 2),
  ('mango', 2023, 'actual', 'export_supermarket', 3),
  ('mango', 2023, 'actual', 'local_sales_combined', 4),
  ('mango', 2023, 'actual', 'actual_production', 5),
  ('mango', 2023, 'plan', 'planned_production', 1),
  ('mango', 2024, 'actual', 'raw_to_packhouse', 1),
  ('mango', 2024, 'actual', 'export_packhouse', 2),
  ('mango', 2024, 'actual', 'local_sales_combined', 3),
  ('mango', 2024, 'actual', 'actual_production', 4),
  ('pomegranate', 2022, 'actual', 'raw_to_packhouse', 1),
  ('pomegranate', 2022, 'actual', 'export_packhouse', 2),
  ('pomegranate', 2022, 'actual', 'export_supermarket', 3),
  ('pomegranate', 2022, 'actual', 'local_sales_combined', 4),
  ('pomegranate', 2022, 'actual', 'actual_production', 5),
  ('pomegranate', 2023, 'actual', 'raw_to_packhouse', 1),
  ('pomegranate', 2023, 'actual', 'export_packhouse', 2),
  ('pomegranate', 2023, 'actual', 'export_supermarket', 3),
  ('pomegranate', 2023, 'actual', 'local_sales_combined', 4),
  ('pomegranate', 2023, 'actual', 'actual_production', 5),
  ('pomegranate', 2023, 'plan', 'planned_production', 1),
  ('pomegranate', 2024, 'actual', 'raw_to_packhouse', 1),
  ('pomegranate', 2024, 'actual', 'export_packhouse', 2),
  ('pomegranate', 2024, 'actual', 'local_sales_combined', 3),
  ('pomegranate', 2024, 'actual', 'vrm', 4),
  ('pomegranate', 2024, 'actual', 'condemned', 5),
  ('pomegranate', 2024, 'actual', 'actual_production', 6)
) as v(product_id, season_year, scenario, code, ord)
join public.farm_metric_sets ms
  on ms.product_id = v.product_id and ms.season_year = v.season_year and ms.scenario = v.scenario
join public.farm_metrics m on m.code = v.code
on conflict (metric_set_id, metric_id) do update set sort_order = excluded.sort_order;

-- down
-- delete from public.farm_metric_set_items i using public.farm_metric_sets s
--   where i.set_id = s.id and s.created_at >= '<applied_at>';
-- delete from public.farm_metric_sets where created_at >= '<applied_at>';
